name: Deploy work flow for Amazon EKS

on:
  pull_request:
    branches:
      - main
    types: [closed]
  push:
    branches:
      - master
      
permissions:
  id-token: write
  contents: read
  
env:
  AWS_REGION: ap-northeast-1
  WEBAPP_TAG: ${{ github.sha }}
  WEBAPP_CONTAINER_NAME: rails-eks

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with: 
        role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      id: login-ecr
      run: aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin 572919087216.dkr.ecr.ap-northeast-1.amazonaws.com

    - name: webapp push to ECR
      id: build-image-webapp
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t 572919087216.dkr.ecr.ap-northeast-1.amazonaws.com/$WEBAPP_CONTAINER_NAME:latest .
        docker push 572919087216.dkr.ecr.ap-northeast-1.amazonaws.com/$WEBAPP_CONTAINER_NAME:latest
        docker tag 572919087216.dkr.ecr.ap-northeast-1.amazonaws.com/$ECR_REGISTRY/$WEBAPP_CONTAINER_NAME:latest 572919087216.dkr.ecr.ap-northeast-1.amazonaws.com/$WEBAPP_CONTAINER_NAME:$WEBAPP_TAG
        docker push 572919087216.dkr.ecr.ap-northeast-1.amazonaws.com/$WEBAPP_CONTAINER_NAME:$WEBAPP_TAG
   